# Generated by Django 3.2.3 on 2021-06-10 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_servicio_cliente'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='servicio',
            table='servicio',
        ),
    ]
