# Generated by Django 3.2.3 on 2021-06-10 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_servicio_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name': 'servicios', 'verbose_name_plural': 'servicios'},
        ),
    ]
