# Generated by Django 3.2.3 on 2021-06-12 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_servicio_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
