# Generated by Django 3.2.3 on 2021-06-07 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_servicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='edad',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='causa',
            new_name='cause',
        ),
    ]
