# Generated by Django 3.2.3 on 2021-06-14 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210612_0025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={},
        ),
        migrations.AlterModelTable(
            name='servicio',
            table=None,
        ),
    ]
