# Generated by Django 3.2.3 on 2021-06-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210617_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Anexos'),
        ),
    ]
