# Generated by Django 3.2.4 on 2021-06-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_servicio_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
