# Generated by Django 3.2.4 on 2021-06-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_servicio_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='phone',
        ),
        migrations.AlterField(
            model_name='telefono',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefono'),
        ),
    ]
