# Generated by Django 3.2.4 on 2021-06-29 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_servicio_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Causas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(null=True, verbose_name='Edad')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('rut', models.CharField(max_length=10)),
                ('files_boleta', models.FileField(upload_to='')),
                ('files_causa', models.FileField(upload_to='')),
                ('files_contrato', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='servicio',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='cause',
            field=models.TextField(max_length=254, null=True, verbose_name='Redactar Causa'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Correo electronico'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='files',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='first_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='phone',
            field=models.CharField(max_length=12, null=True, verbose_name='Telefono'),
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rut', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=30)),
                ('mount', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=10)),
                ('age', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('files_boleta', models.FileField(upload_to='')),
                ('files_causa', models.FileField(upload_to='')),
                ('datetime', models.DateTimeField()),
                ('type_service', models.CharField(max_length=30)),
                ('additional_service', models.CharField(max_length=30, null=True)),
                ('abogado', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
