# Generated by Django 3.2.4 on 2021-06-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210628_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='files_boleta',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='files_causa',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='type_service',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
