# Generated by Django 3.2.4 on 2021-06-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210630_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='files_boleta',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='files_causa',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
