# Generated by Django 3.2.4 on 2021-06-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_causas_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causas',
            name='files_boleta',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='causas',
            name='files_causa',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='causas',
            name='files_contrato',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
