# Generated by Django 3.2.4 on 2021-06-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210630_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='mount',
            field=models.IntegerField(),
        ),
    ]
