# Generated by Django 3.2.4 on 2021-07-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_pagos_mount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='files_boleta',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='files_causa',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
