# Generated by Django 3.2.4 on 2021-07-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210630_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='state',
            field=models.CharField(default='pendiente', max_length=30),
        ),
    ]
