# Generated by Django 3.2.4 on 2021-07-01 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_pagos_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Causa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(null=True, verbose_name='Edad')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('rut', models.CharField(max_length=10)),
                ('files_boleta', models.FileField(blank=True, null=True, upload_to='')),
                ('files_causa', models.FileField(blank=True, null=True, upload_to='')),
                ('files_contrato', models.FileField(blank=True, null=True, upload_to='')),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rut', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=30)),
                ('mount', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(default='pendiente', max_length=30)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='tecnico',
        ),
        migrations.DeleteModel(
            name='Causas',
        ),
        migrations.DeleteModel(
            name='Pagos',
        ),
    ]
